export type AecKind='building'|'level'|'room'|'wall'|'door'|'window'|'column'|'beam'|'slab'|'roof'|'stair'|'cabinet'|'wardrobe'|'countertop'|'panel'|'furniture'|'fixture'|'light'|'material-zone';
export interface Vec2{x:number;y:number}
export interface Box3D extends Vec2{z:number;width:number;height:number;depth:number;rotation?:number}
export interface AecObject extends Box3D{id:string;kind:AecKind;name:string;parentId?:string;levelId?:string;materialId?:string;properties:Record<string,string|number|boolean>;tags:string[]}
export interface Relationship{from:string;type:'contains'|'hosts'|'opens-in'|'supports'|'connected-to'|'assembled-from';to:string}
export interface LevelDefinition{id:string;name:string;elevation:number;height:number}
export interface MaterialDefinition{id:string;name:string;category:'board'|'laminate'|'stone'|'tile'|'paint'|'glass'|'metal'|'wood'|'fabric'|'other';thickness?:number;densityKgM3?:number;costPerM2?:number;wasteFactor?:number;color?:string;texture?:string}
export interface AecModel{id:string;name:string;units:'mm'|'cm'|'m';objects:AecObject[];relationships:Relationship[];materials:MaterialDefinition[];levels:LevelDefinition[]}
export interface Issue{code:string;severity:'error'|'warning'|'info';message:string;objectIds?:string[]}
export interface ValidationReport{valid:boolean;errors:Issue[];warnings:Issue[];info:Issue[]}
const finite=(n:number)=>Number.isFinite(n),positive=(n:number)=>finite(n)&&n>0;
export function validateAecModel(m:AecModel):ValidationReport{const errors:Issue[]=[],warnings:Issue[]=[],info:Issue[]=[];if(!m.id.trim())errors.push({code:'MODEL_ID_REQUIRED',severity:'error',message:'Model ID is required.'});if(!m.name.trim())errors.push({code:'MODEL_NAME_REQUIRED',severity:'error',message:'Model name is required.'});const ids=new Set<string>();for(const o of m.objects){if(!o.id.trim())errors.push({code:'OBJECT_ID_REQUIRED',severity:'error',message:'Every object needs a stable ID.'});if(ids.has(o.id))errors.push({code:'DUPLICATE_ID',severity:'error',message:`Duplicate object ID ${o.id}.`,objectIds:[o.id]});ids.add(o.id);for(const [k,v]of Object.entries({x:o.x,y:o.y,z:o.z,width:o.width,height:o.height,depth:o.depth}))if(!finite(v))errors.push({code:'NON_FINITE_GEOMETRY',severity:'error',message:`${k} is not finite.`,objectIds:[o.id]});if(!positive(o.width)||!positive(o.height)||!positive(o.depth))errors.push({code:'INVALID_SIZE',severity:'error',message:'All dimensions must be positive.',objectIds:[o.id]});if(!o.name.trim())warnings.push({code:'NAME_MISSING',severity:'warning',message:'Object has no descriptive name.',objectIds:[o.id]});}const map=new Set(m.objects.map(o=>o.id));for(const r of m.relationships)if(!map.has(r.from)||!map.has(r.to))errors.push({code:'BROKEN_RELATIONSHIP',severity:'error',message:'Relationship references a missing object.',objectIds:[r.from,r.to]});const rooms=m.objects.filter(o=>o.kind==='room');if(!rooms.length)warnings.push({code:'NO_ROOMS',severity:'warning',message:'No rooms exist.'});for(const o of m.objects.filter(x=>x.kind==='door'||x.kind==='window'))if(!m.relationships.some(r=>r.type==='hosts'&&(r.from===o.id||r.to===o.id)))warnings.push({code:'UNHOSTED_OPENING',severity:'warning',message:'Opening has no host wall.',objectIds:[o.id]});info.push({code:'MODEL_STATS',severity:'info',message:`${m.objects.length} objects, ${rooms.length} rooms, ${m.relationships.length} relationships.`});return{valid:errors.length===0,errors,warnings,info}}
export function areaM2(w:number,h:number){return Math.max(0,w*h)/1e6}
export function volumeM3(o:Box3D){return Math.max(0,o.width*o.height*o.depth)/1e9}
export function snapMm(v:number,grid=50){return !finite(v)||!positive(grid)?v:Math.round(v/grid)*grid}
export function aabbOverlap(a:Box3D,b:Box3D){return a.x<b.x+b.width&&a.x+a.width>b.x&&a.y<b.y+b.height&&a.y+a.height>b.y}
export interface OpeningCheck{openingId:string;hostWallId?:string;valid:boolean;reason?:string}
export function validateOpenings(m:AecModel):OpeningCheck[]{const map=new Map(m.objects.map(o=>[o.id,o]));return m.objects.filter(o=>o.kind==='door'||o.kind==='window').map(o=>{const r=m.relationships.find(x=>x.type==='hosts'&&(x.from===o.id||x.to===o.id));if(!r)return{openingId:o.id,valid:false,reason:'Opening has no host wall.'};const wallId=r.from===o.id?r.to:r.from,w=map.get(wallId);if(!w||w.kind!=='wall')return{openingId:o.id,hostWallId:wallId,valid:false,reason:'Host is not a wall.'};const inside=o.x>=w.x&&o.y>=w.y&&o.x+o.width<=w.x+w.width&&o.y+o.height<=w.y+w.height;return{openingId:o.id,hostWallId:wallId,valid:inside,reason:inside?undefined:'Opening exceeds host wall bounds.'}})}
export interface TileLayout{tileWidth:number;tileHeight:number;grout:number;countX:number;countY:number;wasteAreaM2:number}
export function calculateTileLayout(z:Box3D,tileWidth:number,tileHeight:number,grout=3,rotation:0|90=0):TileLayout{const tw=rotation?tileHeight:tileWidth,th=rotation?tileWidth:tileHeight;const countX=Math.ceil(z.width/Math.max(1,tw+grout)),countY=Math.ceil(z.height/Math.max(1,th+grout));return{tileWidth,tileHeight,grout,countX,countY,wasteAreaM2:Math.max(0,countX*countY*tw*th/1e6-areaM2(z.width,z.height))}}
export interface CeilingPlan{areaM2:number;perimeterMm:number;coveLengthMm:number;downlightCount:number;accessPanels:number}
export function designFalseCeiling(r:Box3D,opt:{cove?:boolean;downlightSpacingMm?:number}={}):CeilingPlan{const area=areaM2(r.width,r.height),perimeter=2*(r.width+r.height),spacing=opt.downlightSpacingMm??1800;return{areaM2:area,perimeterMm:perimeter,coveLengthMm:opt.cove?perimeter:0,downlightCount:Math.max(1,Math.round(r.width*r.height/(spacing*spacing))),accessPanels:Math.max(1,Math.ceil(area/12))}}
export interface LightPlan{luxTarget:number;lumensRequired:number;fixtureCount:number;averageLux:number}
export function calculateLighting(r:Box3D,luxTarget=300,lumensPerFixture=1200,utilization=.7):LightPlan{const a=areaM2(r.width,r.height),required=a*luxTarget/Math.max(.1,utilization),count=Math.max(1,Math.ceil(required/Math.max(1,lumensPerFixture)));return{luxTarget,lumensRequired:required,fixtureCount:count,averageLux:count*lumensPerFixture*utilization/Math.max(.001,a)}}
export interface DrawingDimension{id:string;from:Vec2;to:Vec2;valueMm:number;label:string}
export function autoDimensions(objects:AecObject[]):DrawingDimension[]{return objects.flatMap(o=>[{id:o.id+'-W',from:{x:o.x,y:o.y},to:{x:o.x+o.width,y:o.y},valueMm:o.width,label:Math.round(o.width)+' mm'},{id:o.id+'-H',from:{x:o.x,y:o.y},to:{x:o.x,y:o.y+o.height},valueMm:o.height,label:Math.round(o.height)+' mm'}])}
export interface BomLine{code:string;description:string;category:string;quantity:number;unit:string;materialId?:string;areaM2:number;volumeM3:number}
export function extractBom(m:AecModel):BomLine[]{const map=new Map<string,BomLine>();for(const o of m.objects){const code=o.kind.toUpperCase()+'-'+(o.materialId??'GENERIC'),line=map.get(code)??{code,description:o.materialId?(m.materials.find(x=>x.id===o.materialId)?.name??o.kind):o.kind,category:o.kind,quantity:0,unit:'nos',materialId:o.materialId,areaM2:0,volumeM3:0};line.quantity++;line.areaM2+=areaM2(o.width,o.height);line.volumeM3+=volumeM3(o);map.set(code,line)}return[...map.values()]}
export interface CostScenario{name:string;materialMultiplier:number;labourMultiplier:number;wasteMultiplier:number}
export function optimizeCost(m:AecModel,scenarios:CostScenario[],opt:{labourRate?:number;taxRate?:number;currency?:string}={}){const bom=extractBom(m),baseMaterial=bom.reduce((s,l)=>s+l.areaM2*(l.materialId?m.materials.find(x=>x.id===l.materialId)?.costPerM2??0:0),0),baseLabour=m.objects.length*(opt.labourRate??150);return scenarios.map(s=>{const material=baseMaterial*s.materialMultiplier,labour=baseLabour*s.labourMultiplier,waste=material*Math.max(0,s.wasteMultiplier-1),subtotal=material+labour+waste,tax=subtotal*Math.max(0,opt.taxRate??0);return{scenario:s,material,labour,waste,subtotal,tax,total:subtotal+tax,currency:opt.currency??'INR'}}).sort((a,b)=>a.total-b.total)}
export interface ProductionPart{id:string;cabinetId:string;name:string;width:number;height:number;thickness:number;material:string;grainLocked?:boolean}
export interface ProductionConstraint{maxBoardWidth:number;maxBoardHeight:number;kerf:number;grainLocked:boolean}
export interface NestPlacement extends ProductionPart{x:number;y:number;rotated:boolean}
export interface NestBoard{width:number;height:number;material:string;placements:NestPlacement[];utilization:number}
export function optimizeNesting(parts:ProductionPart[],boards:Array<{width:number;height:number;material:string}>,c:ProductionConstraint){const rem=[...parts].sort((a,b)=>b.width*b.height-a.width*a.height),out:NestBoard[]=[];for(const b of boards){const board:NestBoard={...b,placements:[],utilization:0};for(let i=rem.length-1;i>=0;i--){const p=rem[i];if(p.material!==b.material||p.width>c.maxBoardWidth||p.height>c.maxBoardHeight)continue;const candidates=[{w:p.width,h:p.height,r:false},...(c.grainLocked||p.grainLocked||p.width===p.height?[]:[{w:p.height,h:p.width,r:true}])];let placed:NestPlacement|undefined;for(const q of candidates){for(let y=0;y+q.h<=b.height&&!placed;y+=25)for(let x=0;x+q.w<=b.width&&!placed;x+=25)if(!board.placements.some(n=>aabbOverlap({...n,z:0,depth:p.thickness},{x,y,z:0,width:q.w,height:q.h,depth:p.thickness}))){placed={...p,width:q.w,height:q.h,x,y,rotated:q.r}}}if(placed){board.placements.push(placed);rem.splice(i,1)}}board.utilization=b.width*b.height?board.placements.reduce((s,p)=>s+p.width*p.height,0)/(b.width*b.height):0;out.push(board);if(!rem.length)break}const boardArea=out.reduce((s,b)=>s+b.width*b.height,0)/1e6,used=out.reduce((s,b)=>s+b.placements.reduce((a,p)=>a+p.width*p.height,0),0)/1e6;return{boards:out,unplaced:rem,wasteM2:Math.max(0,boardArea-used),utilization:boardArea?used/boardArea:0}}
export type AiToolName='create_wall'|'create_room'|'place_opening'|'assign_material'|'create_kitchen'|'create_wardrobe'|'validate_model'|'generate_boq'|'generate_drawings'|'optimize_cost'|'optimize_nesting';
export interface AiToolCall{tool:AiToolName;args:Record<string,string|number|boolean>;rationale:string;requiresApproval:boolean}
export function planAiToolCall(request:string):AiToolCall{const q=request.toLowerCase();if(/nest|cutlist|cnc|waste/.test(q))return{tool:'optimize_nesting',args:{},rationale:'Manufacturing optimization requested.',requiresApproval:true};if(/cost|price|budget/.test(q))return{tool:'optimize_cost',args:{},rationale:'Cost optimization requested.',requiresApproval:true};if(/drawing|dimension|elevation/.test(q))return{tool:'generate_drawings',args:{},rationale:'Documentation requested.',requiresApproval:false};if(/boq|quantity/.test(q))return{tool:'generate_boq',args:{},rationale:'Quantity schedule requested.',requiresApproval:false};if(/validate|clash|conflict|check/.test(q))return{tool:'validate_model',args:{},rationale:'Model verification requested.',requiresApproval:false};if(/wardrobe/.test(q))return{tool:'create_wardrobe',args:{request},rationale:'Wardrobe assembly requested.',requiresApproval:true};if(/kitchen|cabinet/.test(q))return{tool:'create_kitchen',args:{request},rationale:'Kitchen assembly requested.',requiresApproval:true};if(/material|tile|finish/.test(q))return{tool:'assign_material',args:{request},rationale:'Material assignment requested.',requiresApproval:true};if(/door|window|opening/.test(q))return{tool:'place_opening',args:{request},rationale:'Opening placement requested.',requiresApproval:true};return{tool:/wall/.test(q)?'create_wall':'create_room',args:{request},rationale:'Editable spatial design operation requested.',requiresApproval:true}}
