/* Parametric interior/manufacturing assemblies. All dimensions are mm. */
export interface CabinetSpec { id:string; width:number; height:number; depth:number; carcass:number; back:number; shelves:number; materialId:string; edgeBand:number; doors:number; drawers:number }
export interface Panel { id:string; assemblyId:string; role:'left'|'right'|'top'|'bottom'|'back'|'shelf'|'door'|'drawer-front'; width:number; height:number; thickness:number; materialId:string; edge:{left:number;right:number;top:number;bottom:number}; grainLocked:boolean }
const positive=(n:number)=>Number.isFinite(n)&&n>0;
export function validateCabinetSpec(s:CabinetSpec):string[]{const e:string[]=[];for(const [k,v] of Object.entries(s))if(['width','height','depth','carcass','back'].includes(k)&&typeof v==='number'&&!positive(v))e.push(`${k} must be positive`);if(s.doors<0||s.drawers<0||s.shelves<0)e.push('counts cannot be negative');if(s.width<2*s.carcass)e.push('width is too small for carcass');return e}
export function buildCabinet(s:CabinetSpec):Panel[]{const err=validateCabinetSpec(s);if(err.length)throw new Error(err.join('; '));const innerW=s.width-2*s.carcass;const innerH=s.height-2*s.carcass;const panels:Panel[]=[];const add=(role:Panel['role'],w:number,h:number,i:number,grain=true)=>panels.push({id:`${s.id}-${role}-${i+1}`,assemblyId:s.id,role,width:w,height:h,thickness:s.carcass,materialId:s.materialId,edge:{left:role==='left'?s.edgeBand:0,right:role==='right'?s.edgeBand:0,top:role==='door'?s.edgeBand:0,bottom:role==='door'?s.edgeBand:0},grainLocked:grain});
 add('left',s.depth-s.back,s.height,0);add('right',s.depth-s.back,s.height,1);add('top',innerW,s.depth-s.back,0);add('bottom',innerW,s.depth-s.back,1);add('back',innerW,innerH,0);for(let i=0;i<s.shelves;i++)add('shelf',innerW,s.depth-s.back,i);for(let i=0;i<s.doors;i++)add('door',s.width/Math.max(1,s.doors),s.height,i);for(let i=0;i<s.drawers;i++)add('drawer-front',s.width/Math.max(1,s.drawers),Math.max(100,s.height/Math.max(1,s.drawers)),i);return panels}
export interface KitchenRun { id:string;width:number;height:number;depth:number;modules:number;countertopThickness:number;toeKick:number;materialId:string }
export function buildKitchenRun(s:KitchenRun):CabinetSpec[]{if(!positive(s.width)||!positive(s.height)||!positive(s.depth))throw new Error('Kitchen dimensions must be positive');const count=Math.max(1,Math.round(s.modules));const moduleWidth=s.width/count;return Array.from({length:count},(_,i)=>({id:`${s.id}-M${i+1}`,width:moduleWidth,height:s.height,depth:s.depth,carcass:18,back:6,shelves:1,materialId:s.materialId,edgeBand:1,doors:1,drawers:i%3===0?3:0}))}
export interface WardrobeSpec { id:string;width:number;height:number;depth:number;sections:number;loftHeight:number;materialId:string;sliding:boolean }
export function buildWardrobe(s:WardrobeSpec):CabinetSpec[]{if(s.sections<1||s.height<=s.loftHeight)throw new Error('Invalid wardrobe sections/loft');const sectionW=s.width/s.sections;return Array.from({length:s.sections},(_,i)=>({id:`${s.id}-S${i+1}`,width:sectionW,height:s.height-s.loftHeight,depth:s.depth,carcass:18,back:6,shelves:2,materialId:s.materialId,edgeBand:1,doors:1,drawers:2}))}
