import {ModelElement,ValidationIssue} from './model';
export interface PanelPart {id:string;name:string;material:string;length:number;width:number;thickness:number;quantity:number;edgeBanding:string[];grain:'length'|'width'|'none'}
export interface CutPlan {boardId:string;material:string;length:number;width:number;thickness:number;parts:PanelPart[];utilization:number;wasteArea:number}
export interface WorkOrder {id:string;projectId:string;status:'draft'|'qc'|'approved'|'released'|'cutting'|'machining'|'assembly'|'packed'|'shipped'|'installed'|'blocked';createdAt:string;parts:PanelPart[];issues:ValidationIssue[]}
export function cabinetPanels(cabinet:ModelElement,material='18mm MDF'):PanelPart[]{const q=cabinet.metadata?.quantity?Number(cabinet.metadata.quantity):1;const W=cabinet.width,H=cabinet.height,D=cabinet.depth;return [{id:`${cabinet.id}-side-l`,name:`${cabinet.name} Side L`,material,length:H,width:D,thickness:18,quantity:q,edgeBanding:['front'],grain:'length'},{id:`${cabinet.id}-side-r`,name:`${cabinet.name} Side R`,material,length:H,width:D,thickness:18,quantity:q,edgeBanding:['front'],grain:'length'},{id:`${cabinet.id}-top`,name:`${cabinet.name} Top`,material,length:W,width:D,thickness:18,quantity:q,edgeBanding:['front'],grain:'length'},{id:`${cabinet.id}-bottom`,name:`${cabinet.name} Bottom`,material,length:W,width:D,thickness:18,quantity:q,edgeBanding:['front'],grain:'length'}]}
export function generateCutlist(elements:ModelElement[]){return elements.filter(e=>['cabinet','panel'].includes(e.kind)).flatMap(e=>cabinetPanels(e))}
export function validateManufacturing(parts:PanelPart[]):ValidationIssue[]{const issues:ValidationIssue[]=[];for(const p of parts){if(p.length<=0||p.width<=0||p.thickness<=0)issues.push({severity:'error',code:'PANEL_DIMENSIONS',message:`Invalid dimensions for ${p.name}`});if(p.length>5000||p.width>2500)issues.push({severity:'warning',code:'BOARD_SIZE',message:`Large panel may exceed standard sheet size: ${p.name}`});if(p.quantity<1||!Number.isInteger(p.quantity))issues.push({severity:'error',code:'PANEL_QUANTITY',message:`Invalid quantity for ${p.name}`})}return issues}
export function nextWorkOrderStatus(current:WorkOrder['status'],qcPassed:boolean):WorkOrder['status']{const flow:WorkOrder['status'][]=['draft','qc','approved','released','cutting','machining','assembly','packed','shipped','installed'];if(!qcPassed&&['qc','approved','released'].includes(current))return 'blocked';const i=flow.indexOf(current);return i<0||i===flow.length-1?current:flow[i+1]}
export function optimizeSimple(parts:PanelPart[],boardL=2440,boardW=1220){const total=parts.reduce((a,p)=>a+p.length*p.width*p.quantity,0);const boardArea=boardL*boardW;const boards=Math.max(1,Math.ceil(total/boardArea));const utilization=total/(boards*boardArea);return {boards,utilization,wasteArea:boards*boardArea-total}}
